[workspace]
members = [
	"moq-transfork",
	"moq-relay",
	"moq-clock",
	"moq-dir",
	"moq-native",
	"moq-warp",
]
resolver = "2"

[workspace.dependencies]
# Make it easy to test web-transport changes
web-transport = { path = "../web-transport-rs/web-transport", version = "0.5" }

# TODO finish switching to tracing
env_logger = "0.11"
log = { version = "0.4", features = ["std"] }

# Use debug symbols in production until things are more stable
[profile.release]
debug = true
