[workspace]
members = [
	"moq-transport",
	"moq-relay",
	"moq-pub",
	"moq-sub",
	"moq-api",
	"moq-clock",
	"moq-dir",
	"moq-native",
	"moq-catalog",
]
resolver = "2"

# Use debug symbols in production until things are more stable
[profile.release]
debug = true
