[package]
name = "hang"
description = "Media over QUIC"
authors = ["Luke Curley <kixelated@gmail.com>"]
repository = "https://github.com/kixelated/moq"
license = "MIT OR Apache-2.0"

version = "0.3.0"
edition = "2021"

keywords = ["quic", "http3", "webtransport", "media", "live"]
categories = ["multimedia", "network-programming", "web-programming"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.10"
futures = "0.3"
hex = "0.4"
lazy_static = "1"
moq-lite = { workspace = true, features = ["serde"] }
mp4-atom = { version = "0.8.1", features = ["tokio", "bytes", "serde"] }
regex = "1"
serde = { workspace = true }
serde_json = "1"
serde_with = { version = "3", features = ["hex"] }
thiserror = "2"
tokio = { workspace = true, features = ["macros"] }
tracing = "0.1"
web-async = { workspace = true }

[dependencies.derive_more]
version = "2"
features = ["from", "display", "debug"]
