[package]
name = "moq-transport"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Fork of h3 with WebTransport support
h3 = { git = "https://github.com/security-union/h3", branch = "add-webtransport" }
h3-quinn = { git = "https://github.com/security-union/h3", branch = "add-webtransport" }
h3-webtransport = { git = "https://github.com/security-union/h3", branch = "add-webtransport" }
quinn = { version = "0.10", default-features = false, features = ["runtime-tokio", "tls-rustls", "ring"] }
quinn-proto = "0.10"
http = "0.2"

# Crypto dependencies
ring = "0.16"
rustls = { version = "0.21", features = ["dangerous_configuration"] }
rustls-pemfile = "1.0.2"

# Async stuff
tokio = { version = "1.27", features = ["full"] }
futures = "0.3"

# Encoding
bytes = "1"

# Logging
clap = { version = "4.0", features = [ "derive" ] }
log = { version = "0.4", features = ["std"] }
env_logger = "0.9.3"

# Utility
anyhow = "1.0.70"
thiserror = "1.0.21"
async-trait = "0.1"
